#!/usr/bin/env bash
# task

PID_FILE="/tmp/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"

case "$1" in
  start)
    "$PROCESS_SCRIPT" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
    ;;
  stop)
    kill "$(cat "$PID_FILE")"
    rm -f "$PID_FILE"
    echo "manage_my_process stopped"
    ;;
  restart)
    kill "$(cat "$PID_FILE")"
    rm -f "$PID_FILE"
    "$PROCESS_SCRIPT" &
    echo $! > "$PID_FILE"
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
