#!/usr/bin/env bash
# task
echo $$ > /tmp/myscript.pid

clean1() {
    rm -f /tmp/myscript.pid
    exit
}

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "cleanup" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
